# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog abount Linux, Technologies and Life
email: undying.k@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog I will describe situations that I meet in my life
  when working with a variety of technologies. This includes any kind
  of computer technologies, Open Software, Linux and many more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://undying.github.io" # the base hostname & protocol for your site
github_username:  undying
linkedin_username: bozhok-denis
facebook_id: 100009455237641
facebook_username: Kron

# Build settings
markdown: kramdown

paginate: 7

exclude: [ vendor ]
